# Generated by Django 4.1.7 on 2023-04-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0003_manutencao_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.veiculo'),
        ),
    ]
